version: 0.0
os: windows
files:
    - source: /
      destination: C:\CategoricallyApp
hooks:
  BeforeInstall:
    - location: /BeforeInstall.ps1
  AfterInstall:
    - location: /AfterInstall.ps1
      timeout: 300
  ApplicationStart:
    - location: /ApplicationStart.ps1
      timeout: 300
  ValidateService:
    - location: /ValidateService.ps1
      timeout: 300