version: 0.0
os: windows
files:
    - source: /publish
      destination: C:\CategoricallyApp
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.ps1
  AfterInstall:
    - location: scripts/AfterInstall.ps1
      timeout: 300
  ApplicationStart:
    - location: scripts/ApplicationStart.ps1
      timeout: 300
  ValidateService:
    - location: scripts/ValidateService.ps1
      timeout: 300